# Generated by Django 4.2.2 on 2023-07-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourIni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hourIni', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('inicio', models.ManyToManyField(to='schedule.hourini')),
                ('usuario1', models.ForeignKey(blank=True, default=99, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_usuario1', to='usuarios.usuario')),
            ],
        ),
    ]
