# Generated by Django 4.2.2 on 2023-07-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourIni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hourIni', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HourIni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.hourini')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('usuario', models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
