# Generated by Django 4.2.2 on 2023-07-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleag',
            old_name='HourIni',
            new_name='hourIni',
        ),
    ]
