# Generated by Django 4.2.2 on 2023-07-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_scheduleag_hourini_scheduleag_hourini'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Date',
        ),
    ]
