# Generated by Django 4.2.2 on 2023-07-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='observacion',
        ),
    ]
