# Generated by Django 4.2.2 on 2023-07-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
